# Generated by Django 5.2.3 on 2025-06-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barcode_number', models.CharField(blank=True, max_length=13, unique=True)),
                ('barcode_image', models.ImageField(blank=True, upload_to='barcodes/')),
            ],
        ),
    ]
