# Generated by Django 5.2.3 on 2025-06-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
